# Generated by Django 5.2.15 on 2026-06-24 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="featured_image",
            field=models.ImageField(
                default="blog/default.webp", upload_to="blog/featured/%Y/%m/"
            ),
        ),
    ]
