# Generated by Django 5.2.15 on 2026-09-19 18:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='موجود است؟'),
        ),
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.PositiveIntegerField(blank=True, help_text='اگر خالی بگذارید، به\u200cجای عدد «استعلام قیمت» نمایش داده می\u200cشود.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت (تومان)'),
        ),
    ]