# Generated by Django 5.2.15 on 2026-09-12 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_post_featured_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="price",
            field=models.CharField(default=1000000, max_length=200),
            preserve_default=False,
        ),
    ]
